[package]
name = "bukara-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
env_logger = "0.11.5"
lazy_static = "1.5.0"
log = "0.4.22"
notify-rust = "4.11.3"
tokio = { version = "1.41.1", features = ["full"] }
zbus = "5.1.1"
